- hosts: all
  become: yes
  tasks:
        - name: Install gvisor
          shell: |
            ARCH=$(uname -m)
            URL=https://storage.googleapis.com/gvisor/releases/release/latest/${ARCH}
            wget ${URL}/runsc ${URL}/runsc.sha512 \
              ${URL}/containerd-shim-runsc-v1 ${URL}/containerd-shim-runsc-v1.sha512
            sha512sum -c runsc.sha512 \
              -c containerd-shim-runsc-v1.sha512
            rm -f *.sha512
            chmod a+rx runsc containerd-shim-runsc-v1
            sudo mv runsc containerd-shim-runsc-v1 /usr/local/bin
          tags:
            - gvisor

        - name: Upload containerd config
          copy:
            src: "{{ ansible_dir }}/resources/containerd-config.toml"
            dest: /etc/containerd/config.toml
          tags:
            - gvisor
        
        - name: Restart containerd
          shell: |
            systemctl restart containerd
          tags:
            - gvisor
        
- hosts: master
  become: ansible
  tasks:
        - name: Create gvisor runtime class
          shell: |
            kubectl apply -f - <<EOF
              apiVersion: node.k8s.io/v1
              kind: RuntimeClass
              metadata:
                name: gvisor
              handler: runsc
            EOF
          tags:
            - gvisor