---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.160-192.168.0.165
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: myportal-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip--pool