- hosts: localhost
  become: true
  tasks:
  - name: Set architecture specific variables
    set_fact:
      arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

###############################################################
# curl https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor | sudo tee /usr/share/keyrings/kubernetes.gpg > /dev/null
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/kubernetes.gpg]  https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
# sudo apt-get update
# sudo apt-get install kubectl
###############################################################
  - name: kubernetes repository keyring
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
      dest: /usr/share/keyrings/kubernetes.gpg.armored

  - name: De-Armor kubernetes GPG key
    shell: gpg --dearmor < /usr/share/keyrings/kubernetes.gpg.armored > /usr/share/keyrings/kubernetes.gpg
    args:
        creates: /usr/share/keyrings/kubernetes.gpg

  - name: kubeadm repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{arch}} signed-by=/usr/share/keyrings/kubernetes.gpg]  https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
      state: present
      filename: kubernetes
      update_cache: false

  - name: Install kubectl
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
      force: true
    vars:
      packages:
      - kubectl=1.31.0-1.1

###############################################################
# curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
# sudo apt-get install apt-transport-https --yes
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
# sudo apt-get update
# sudo apt-get install helm
###############################################################
  - name: Add helm GPG
    ansible.builtin.get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /usr/share/keyrings/helm.gpg.armored
  
  - name: De-Armor helm gpg
    shell: gpg --dearmor < /usr/share/keyrings/helm.gpg.armored > /usr/share/keyrings/helm.gpg
    args:
      creates: /usr/share/keyrings/helm.gpg

  - name: Add helm to apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{arch}} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
      state: present
      filename: helm
      update_cache: false

  - name: Install helm
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
      force: true
    vars:
        packages:
        - helm=3.16.3-1


